name: CI-CD-Pipeline-to-AWS-ElasticBeastalk  # В будущем этот скрипт можно поменятьна любой application и использовать для deploy любого application.
env:  #Назначаем глобальные переменные которые нам понадобяться
  EB_PACKAGE_S3_BUCKET_NAME : "vasya-flask-application-packages" # Это имя S3 Bucket где будут храниться все наши пакеты 
  EB_APPLICATION_NAME       : "MyFlask"      # Это имя Elastic Beanstack которыймы сделали
  EB_EVIRONMENT_NAME        : "Myflask-env"  # Это имя Elastic Beanstack создает автоматически , можно поменять (prod, staged)
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"  # Это файл который будет использоваться. ${{ github.sha }} - Это hash коммита
  AWS_REGION_NAME           : "us-west-2"

on:
  push:
    branches: 
      - master
jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone our repo
      uses: actions/checkout@v3            # Клонируем наш репозиторий во внутрь VM это внутренние скрипты github

    - name: Create ZIP deployment package  # Архивируем наш репозиторий в один файл
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git* # Архивируем все файлы в наш архив кроме файлов git
  

    - name: Configure my AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-acces-key-id     : ${{ secrets.MY_AWS_ACCESS_KEY }} # Посылаем в наш скрипт configure-aws-credentials@v1 наш секретный ключ из хранилища Github Secrets
        aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }} # Посылаем SECRET key
        aws-region           : ${{ env.AWS_REGION_NAME }}       # Засылаем наш регион
    
    - name: Copy Deployment package to S3 Bucket
      run: aws S3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ EB_PACKAGE_S3_BUCKET_NAME }}/  # Копируем наш файл в S3 Bucket (это команда aws)
      
    - name: Print Happy Message for CI finish
      run : echo "CI Pipeline part finished successfully"
